class PlaceNotFoundError(Exception):
    pass

class PlaceAlreadyExists(Exception):
    pass